Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web01" do |web01|
    web01.vm.box = "centos/7"
    web01.vm.network "private_network", ip: "192.168.33.15"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    web01.vm.provision "shell", inline: <<-SHELL
      yum install httpd wget unzip -y
      systemctl start httpd
      systemctl enable httpd
      cd /tmp/
      wget https://www.tooplate.com/zip-templates/2121_wave_cafe.zip
      unzip -o 2121_wave_cafe.zip
      cp -r 2121_wave_cafe/* /var/www/html/
      systemctl restart httpd
    SHELL
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "hashicorp/bionic64"
    db01.vm.network "private_network", ip: "192.168.33.16"
    # config.vm.provider "virtualbox" do |vb|
      # vb.memory = "1024"
    # end
  end
end
