- name: Restart NTP on RedHat
  ansible.builtin.service:
    name: ntpd
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Restart NTP on Debian
  ansible.builtin.service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"