apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      # key-value label here must match the one below !!!
      tier: frontend

  # template is essentially defining a Pod
  template:
    metadata:
      labels:
        # key-value label here must match the one above !!!
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
